name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}


jobs:
  build-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: "latest"
          activate-environment: cgal
          channels: conda-forge
          python-version: 3.7

      - name: build (mac)
        if: matrix.os == 'macos-latest'
        run: |
          conda install eigen=3.3 boost-cpp gmp mpfr cgal-cpp=5.2 pybind11 compas -y
          pip install -r requirements-dev.txt

      - name: build (windows)
        if: matrix.os == 'windows-latest'
        run: |
          conda install eigen=3.3 boost-cpp mpir mpfr cgal-cpp=5.2 pybind11 compas -y
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          invoke lint

      - name: Test with pytest
        run: |
          invoke test

      - name: Test build docs
        run: |
          invoke docs
